# Generated by Django 5.1.15 on 2026-07-18 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MilestoneAck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=80, unique=True)),
                ('dismissed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'monitoring_milestone_ack',
            },
        ),
    ]
