# Generated by Django 5.1.15 on 2026-07-23 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='importrow',
            name='group_meta',
            field=models.JSONField(default=dict),
        ),
    ]
