# Generated by Django 5.1.15 on 2026-06-15 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorder',
            name='credit_note_number',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='returned_minor',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='salesorderline',
            name='delivered_qty',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='salesorderline',
            name='returned_qty',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('confirmed', 'Confirmed'), ('partially_delivered', 'Partially delivered'), ('delivered', 'Delivered'), ('invoiced', 'Invoiced'), ('paid', 'Paid'), ('returned', 'Returned'), ('cancelled', 'Cancelled')], default='draft', max_length=24),
        ),
    ]
