# Generated by Django 5.1.15 on 2026-06-15 12:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('sales', '0002_salesorder_credit_note_number_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('number', models.CharField(max_length=32, unique=True)),
                ('quote_date', models.DateField()),
                ('warehouse_code', models.CharField(max_length=32)),
                ('currency', models.CharField(default='EGP', max_length=3)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('converted', 'Converted'), ('cancelled', 'Cancelled')], default='draft', max_length=16)),
                ('subtotal_minor', models.BigIntegerField(default=0)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_reason', models.CharField(blank=True, default='', max_length=255)),
                ('converted_order_number', models.CharField(blank=True, default='', max_length=32)),
                ('notes', models.CharField(blank=True, default='', max_length=255)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.branch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quotations', to='sales.customer')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sales_quotation',
                'ordering': ['-quote_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuotationLine',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('line_no', models.IntegerField()),
                ('item_sku', models.CharField(max_length=64)),
                ('description', models.CharField(blank=True, default='', max_length=200)),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=18)),
                ('unit_price_minor', models.BigIntegerField()),
                ('line_total_minor', models.BigIntegerField()),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='sales.quotation')),
            ],
            options={
                'db_table': 'sales_quotation_line',
                'ordering': ['quotation', 'line_no'],
            },
        ),
        migrations.AddIndex(
            model_name='quotation',
            index=models.Index(fields=['status'], name='sales_quota_status_de197d_idx'),
        ),
        migrations.AddIndex(
            model_name='quotation',
            index=models.Index(fields=['customer'], name='sales_quota_custome_386f35_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='quotationline',
            unique_together={('quotation', 'line_no')},
        ),
    ]
