# Generated by Django 5.1.15 on 2026-06-15 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_salesorder_approved_salesorder_approved_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorder',
            name='tax_code',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='tax_minor',
            field=models.BigIntegerField(default=0),
        ),
    ]
