# Generated by Django 5.1.15 on 2026-07-02 08:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('identity', '0009_orgpreferences_order_cancel_until'),
        ('sales', '0006_customer_department_customer_team_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='quotation',
            index=models.Index(fields=['-quote_date', '-created_at'], name='sales_quota_quote_d_a405be_idx'),
        ),
        migrations.AddIndex(
            model_name='salesorder',
            index=models.Index(fields=['-order_date', '-created_at'], name='sales_order_order_d_41e4ff_idx'),
        ),
    ]
