# Generated by Django 5.1.15 on 2026-07-17 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0007_quotation_sales_quota_quote_d_a405be_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='custom_data',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
