# Generated by Django 5.1.15 on 2026-07-20 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0009_pendingpayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='validity_until',
            field=models.DateField(blank=True, null=True),
        ),
    ]
