# Generated by Django 5.1.15 on 2026-07-21 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0010_quotation_validity_until'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='national_id',
            field=models.CharField(blank=True, default='', max_length=14),
        ),
        migrations.AddField(
            model_name='customer',
            name='tax_registration_number',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
    ]
