# Generated by Django 5.1.15 on 2026-07-22 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0011_customer_national_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorder',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
