# Generated by Django 5.1.15 on 2026-06-14 12:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IdempotencyRecord',
            fields=[
                ('key', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('instance_id', models.UUIDField()),
                ('node_id', models.UUIDField()),
                ('response', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'workflow_idempotency_record',
            },
        ),
        migrations.CreateModel(
            name='Workflow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('version', models.IntegerField(default=1)),
                ('status', models.CharField(default='active', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'workflow',
            },
        ),
        migrations.CreateModel(
            name='WorkflowNode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=64)),
                ('type', models.CharField(choices=[('start', 'Start'), ('api_call', 'Api Call'), ('approval', 'Approval'), ('condition', 'Condition'), ('script', 'Script'), ('end', 'End')], max_length=16)),
                ('config', models.JSONField(default=dict)),
                ('position', models.JSONField(default=dict)),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='workflow.workflow')),
            ],
            options={
                'db_table': 'workflow_node',
                'unique_together': {('workflow', 'key')},
            },
        ),
        migrations.CreateModel(
            name='WorkflowInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('waiting', 'Waiting'), ('failed', 'Failed'), ('completed', 'Completed')], default='pending', max_length=16)),
                ('context', models.JSONField(default=dict)),
                ('error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('started_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instances', to='workflow.workflow')),
                ('current_node', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='workflow.workflownode')),
            ],
            options={
                'db_table': 'workflow_instance',
            },
        ),
        migrations.CreateModel(
            name='WorkflowEdge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('condition', models.JSONField(blank=True, null=True)),
                ('ordering', models.IntegerField(default=0)),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edges', to='workflow.workflow')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='out_edges', to='workflow.workflownode')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_edges', to='workflow.workflownode')),
            ],
            options={
                'db_table': 'workflow_edge',
            },
        ),
        migrations.CreateModel(
            name='NodeExecution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('waiting', 'Waiting'), ('failed', 'Failed'), ('completed', 'Completed')], default='pending', max_length=16)),
                ('attempt', models.IntegerField(default=1)),
                ('input', models.JSONField(blank=True, null=True)),
                ('output', models.JSONField(blank=True, null=True)),
                ('error', models.TextField(blank=True, default='')),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='node_runs', to='workflow.workflowinstance')),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='workflow.workflownode')),
            ],
            options={
                'db_table': 'workflow_node_execution',
            },
        ),
        migrations.CreateModel(
            name='ExecutionLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('level', models.CharField(choices=[('debug', 'Debug'), ('info', 'Info'), ('warn', 'Warn'), ('error', 'Error')], default='info', max_length=8)),
                ('message', models.CharField(max_length=500)),
                ('data', models.JSONField(blank=True, null=True)),
                ('correlation_id', models.CharField(blank=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('node_execution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='workflow.nodeexecution')),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='workflow.workflowinstance')),
            ],
            options={
                'db_table': 'workflow_execution_log',
                'indexes': [models.Index(fields=['instance'], name='workflow_ex_instanc_2bb99d_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='workflowinstance',
            index=models.Index(fields=['status'], name='workflow_in_status_3dc290_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowedge',
            index=models.Index(fields=['workflow', 'source', 'ordering'], name='workflow_ed_workflo_24e5bb_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='workflowedge',
            unique_together={('source', 'ordering')},
        ),
        migrations.AddIndex(
            model_name='nodeexecution',
            index=models.Index(fields=['instance'], name='workflow_no_instanc_dbe31b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='nodeexecution',
            unique_together={('instance', 'node', 'attempt')},
        ),
    ]
