# Generated by Django 5.1.15 on 2026-07-22 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0004_alter_workflownode_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflownode',
            name='type',
            field=models.CharField(choices=[('start', 'Start'), ('api_call', 'Api Call'), ('approval', 'Approval'), ('assistant_action', 'Assistant Action'), ('condition', 'Condition'), ('script', 'Script'), ('notification', 'Notification'), ('end', 'End')], max_length=32),
        ),
    ]
