# Generated by Django 5.1.15 on 2026-07-22 13:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0005_notification_node_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowTrigger',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_name', models.CharField(max_length=64)),
                ('condition', models.JSONField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='triggers', to='workflow.workflow')),
            ],
            options={
                'db_table': 'workflow_trigger',
                'indexes': [models.Index(fields=['event_name', 'is_active'], name='workflow_tr_event_n_43630a_idx')],
            },
        ),
    ]
