# Generated by Django 5.1.15 on 2026-07-23 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0006_workflowtrigger'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowtrigger',
            name='schedule',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='workflowtrigger',
            name='event_name',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
