# Generated by Django 5.1.15 on 2026-07-20 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricelist',
            name='name_ar',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
