# Generated by Django 5.1.15 on 2026-06-20 09:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0002_user_branch_user_totp_secret'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrgPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_language', models.CharField(choices=[('ar', 'Arabic'), ('en', 'English')], default='ar', max_length=2)),
                ('default_theme', models.CharField(choices=[('system', 'System'), ('light', 'Light'), ('dark', 'Dark')], default='system', max_length=8)),
                ('default_accent', models.CharField(choices=[('blue', 'Blue'), ('black', 'Black'), ('green', 'Green'), ('purple', 'Purple'), ('orange', 'Orange'), ('red', 'Red')], default='blue', max_length=8)),
                ('default_landing', models.CharField(blank=True, default='', max_length=120)),
                ('company_name', models.CharField(blank=True, default='', max_length=160)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'org preferences',
                'db_table': 'identity_org_preferences',
            },
        ),
        migrations.CreateModel(
            name='UserPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(blank=True, default='', max_length=120)),
                ('job_title', models.CharField(blank=True, default='', max_length=120)),
                ('phone', models.CharField(blank=True, default='', max_length=40)),
                ('preferred_language', models.CharField(blank=True, choices=[('ar', 'Arabic'), ('en', 'English')], default='', max_length=2)),
                ('time_zone', models.CharField(blank=True, default='Africa/Cairo', max_length=64)),
                ('date_format', models.CharField(choices=[('iso', '2026-06-20'), ('dmy', '20/06/2026'), ('mdy', '06/20/2026')], default='iso', max_length=8)),
                ('time_format', models.CharField(choices=[('24h', '24-hour'), ('12h', '12-hour')], default='24h', max_length=4)),
                ('theme', models.CharField(blank=True, choices=[('system', 'System'), ('light', 'Light'), ('dark', 'Dark')], default='', max_length=8)),
                ('accent_color', models.CharField(blank=True, choices=[('blue', 'Blue'), ('black', 'Black'), ('green', 'Green'), ('purple', 'Purple'), ('orange', 'Orange'), ('red', 'Red')], default='', max_length=8)),
                ('sidebar_style', models.CharField(choices=[('expanded', 'Expanded'), ('compact', 'Compact')], default='expanded', max_length=10)),
                ('density', models.CharField(choices=[('comfortable', 'Comfortable'), ('compact', 'Compact')], default='comfortable', max_length=12)),
                ('font_size', models.CharField(choices=[('small', 'Small'), ('default', 'Default'), ('large', 'Large')], default='default', max_length=8)),
                ('high_contrast', models.BooleanField(default=False)),
                ('reduced_motion', models.BooleanField(default=False)),
                ('keyboard_nav', models.BooleanField(default=False)),
                ('notif_email', models.BooleanField(default=True)),
                ('notif_inapp', models.BooleanField(default=True)),
                ('notif_sound', models.BooleanField(default=False)),
                ('notif_desktop', models.BooleanField(default=False)),
                ('digest_frequency', models.CharField(choices=[('off', 'Off'), ('daily', 'Daily'), ('weekly', 'Weekly')], default='off', max_length=8)),
                ('default_landing', models.CharField(blank=True, default='', max_length=120)),
                ('dashboard_layout', models.JSONField(blank=True, default=dict)),
                ('favorites', models.JSONField(blank=True, default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'user preferences',
                'db_table': 'identity_user_preferences',
            },
        ),
    ]
