# Generated by Django 5.1.15 on 2026-06-20 13:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('identity', '0003_orgpreferences_userpreferences'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(max_length=40)),
                ('limit_minor', models.BigIntegerField(blank=True, null=True)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_limits', to='auth.group')),
            ],
            options={
                'db_table': 'identity_approval_limit',
                'constraints': [models.UniqueConstraint(fields=('role', 'document_type'), name='uniq_role_approval_limit')],
            },
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=80)),
                ('scope', models.CharField(choices=[('all', 'All records'), ('company', 'My company'), ('branch', 'My branch'), ('department', 'My department'), ('team', 'My team'), ('own', 'My records only')], default='all', max_length=12)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_permissions', to='auth.group')),
            ],
            options={
                'db_table': 'identity_role_permission',
                'constraints': [models.UniqueConstraint(fields=('role', 'code'), name='uniq_role_permission')],
            },
        ),
    ]
