# Generated by Django 5.1.15 on 2026-06-26 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0005_user_status_department_user_department_team_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orgpreferences',
            name='is_setup_complete',
            field=models.BooleanField(default=False),
        ),
    ]
