# Generated by Django 5.1.15 on 2026-06-26 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0006_orgpreferences_is_setup_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='orgpreferences',
            name='base_currency',
            field=models.CharField(default='EGP', max_length=3),
        ),
        migrations.AddField(
            model_name='orgpreferences',
            name='country',
            field=models.CharField(blank=True, default='Egypt', max_length=56),
        ),
        migrations.AddField(
            model_name='orgpreferences',
            name='vat_number',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
    ]
