# Generated by Django 5.1.15 on 2026-06-26 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0007_orgpreferences_base_currency_orgpreferences_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orgpreferences',
            name='einvoice_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
