# Generated by Django 5.1.15 on 2026-06-29 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0008_orgpreferences_einvoice_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='orgpreferences',
            name='order_cancel_until',
            field=models.CharField(choices=[('disabled', 'Never'), ('draft', 'Drafts only'), ('confirmed', 'Until confirmed')], default='confirmed', max_length=10),
        ),
    ]
