# Generated by Django 5.1.15 on 2026-07-05 07:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0009_orgpreferences_order_cancel_until'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_key', models.CharField(max_length=60)),
                ('name', models.CharField(max_length=60)),
                ('query', models.TextField(blank=True, default='')),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_views', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'identity_saved_view',
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(fields=('user', 'list_key', 'name'), name='uniq_saved_view_user_list_name')],
            },
        ),
    ]
