# Generated by Django 5.1.15 on 2026-07-20 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0011_apikey'),
    ]

    operations = [
        migrations.AddField(
            model_name='orgpreferences',
            name='assistant_posting_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
