# Generated by Django 5.1.15 on 2026-07-20 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0011_apikey'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='name_ar',
            field=models.CharField(blank=True, default='', max_length=160),
        ),
    ]
