# Generated by Django 5.1.15 on 2026-07-21 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0012_orgpreferences_assistant_posting_enabled'),
        ('identity', '0014_backfill_department_arabic_names'),
    ]

    operations = [
    ]
