/* Formatted on 4/8/2026 9:35:59 AM (QP5 v5.336) */
--DROP TABLE PRD.ATR_E_RECEIPT_HISTORY CASCADE CONSTRAINTS;

CREATE TABLE PRD.ATR_E_RECEIPT_HISTORY
(
    DEBUG_RESULT_ID      NUMBER,
    INVOICE_ID           NUMBER,
    INVOICE_NUMBER       VARCHAR2 (2000 CHAR),
    UUID                 VARCHAR2 (4000 CHAR),
    TYPENAME             VARCHAR2 (4000 CHAR),
    STATUS               VARCHAR2 (4000 CHAR),
    CREATION_DATE        DATE,
    CREATED_BY           NUMBER,
    LAST_UPDATE_BY       NUMBER,
    LAST_UPDATED_DATE    DATE,
    NODE_NAME            VARCHAR2 (200 CHAR)
)
TABLESPACE USERS
PCTUSED 0
PCTFREE 10
INITRANS 1
MAXTRANS 255
STORAGE (INITIAL 64 K
         NEXT 1 M
         MINEXTENTS 1
         MAXEXTENTS UNLIMITED
         PCTINCREASE 0
         BUFFER_POOL DEFAULT)
LOGGING
NOCOMPRESS
NOCACHE
MONITORING;


CREATE INDEX PRD.REC_HISTORY
    ON PRD.ATR_E_RECEIPT_HISTORY (INVOICE_ID, UUID)
    LOGGING
    TABLESPACE USERS
    PCTFREE 10
    INITRANS 2
    MAXTRANS 166
    STORAGE (INITIAL 64 K
             NEXT 1 M
             MINEXTENTS 1
             MAXEXTENTS UNLIMITED
             PCTINCREASE 0
             BUFFER_POOL DEFAULT);

CREATE INDEX PRD.REC_UUID
    ON PRD.ATR_E_RECEIPT_HISTORY (UUID)
    LOGGING
    TABLESPACE USERS
    PCTFREE 10
    INITRANS 2
    MAXTRANS 167
    STORAGE (INITIAL 64 K
             NEXT 1 M
             MINEXTENTS 1
             MAXEXTENTS UNLIMITED
             PCTINCREASE 0
             BUFFER_POOL DEFAULT);