/* Formatted on 4/8/2026 9:39:47 AM (QP5 v5.336) */
--DROP TABLE PRD.ATR_ELECTRONIC_INVOICE_MAPPING_ITEMS CASCADE CONSTRAINTS;

CREATE TABLE PRD.ATR_ELECTRONIC_INVOICE_MAPPING_ITEMS
(
    E_INVOICE_MAPPING_ITEM_ID    NUMBER NOT NULL,
    INVENTORY_ITEM_ID            NUMBER,
    ORCL_ITEM_CODE               VARCHAR2 (500 CHAR),
    EGS_ITEM_CODE                VARCHAR2 (500 CHAR),
    TAXABLE_TYPES                VARCHAR2 (500 CHAR),
    TAX_SUBTYPES                 VARCHAR2 (500 CHAR),
    CREATION_DATE                DATE,
    CREATED_BY                   NUMBER,
    LAST_UPDATE_BY               NUMBER,
    LAST_UPDATED_DATE            DATE,
    UOM                          VARCHAR2 (200 CHAR),
    STATUS                       VARCHAR2 (200 CHAR)
)
TABLESPACE USERS
PCTUSED 0
PCTFREE 10
INITRANS 1
MAXTRANS 255
STORAGE (INITIAL 64 K
         NEXT 1 M
         MINEXTENTS 1
         MAXEXTENTS UNLIMITED
         PCTINCREASE 0
         BUFFER_POOL DEFAULT)
LOGGING
NOCOMPRESS
NOCACHE
MONITORING;


CREATE UNIQUE INDEX PRD.ORCL_ITEM_CODE_U
    ON PRD.ATR_ELECTRONIC_INVOICE_MAPPING_ITEMS (ORCL_ITEM_CODE)
    LOGGING
    TABLESPACE USERS
    PCTFREE 10
    INITRANS 2
    MAXTRANS 255
    STORAGE (INITIAL 64 K
             NEXT 1 M
             MINEXTENTS 1
             MAXEXTENTS UNLIMITED
             PCTINCREASE 0
             BUFFER_POOL DEFAULT);

ALTER TABLE PRD.ATR_ELECTRONIC_INVOICE_MAPPING_ITEMS
    ADD (CONSTRAINT ORCL_ITEM_CODE_U UNIQUE (ORCL_ITEM_CODE) USING INDEX PRD.ORCL_ITEM_CODE_U ENABLE VALIDATE);