/* Formatted on 4/8/2026 9:27:26 AM (QP5 v5.336) */
--DROP TABLE PRD.ATR_E_RECEIPT_DEBUG_RESULT CASCADE CONSTRAINTS;

CREATE TABLE PRD.ATR_E_RECEIPT_DEBUG_RESULT
(
    DEBUG_RESULT_ID           NUMBER NOT NULL,
    URL                       VARCHAR2 (500 CHAR),
    STATUS_CODE               VARCHAR2 (200 CHAR),
    WEB_SERVICE_NAME          VARCHAR2 (4000 CHAR),
    WEB_SERVICE_METHOD        VARCHAR2 (4000 BYTE),
    DEBUG_RESULT              CLOB,
    CREATION_DATE             DATE,
    CREATED_BY                NUMBER,
    LAST_UPDATE_BY            NUMBER,
    LAST_UPDATED_DATE         DATE,
    NODE_NAME                 VARCHAR2 (200 CHAR),
    JSON_WITHOUT_SIGNATURE    CLOB,
    JSON_WITH_SIGNATURE       CLOB,
    SERIALIZATION             CLOB,
    JSON_FOR_SERIALIZE        CLOB,
    UUID                      VARCHAR2 (2000 BYTE),
    FINAL_JSON                CLOB,
    SENT_JSON                 CLOB,
    RESPONSE                  CLOB
)
LOB (DEBUG_RESULT) STORE AS SECUREFILE
    (TABLESPACE USERS
     ENABLE STORAGE IN ROW
     CHUNK 8192
     NOCACHE LOGGING)
LOB (FINAL_JSON) STORE AS SECUREFILE
    (TABLESPACE USERS
     ENABLE STORAGE IN ROW
     CHUNK 8192
     NOCACHE LOGGING)
LOB (JSON_FOR_SERIALIZE) STORE AS SECUREFILE
    (TABLESPACE USERS
     ENABLE STORAGE IN ROW
     CHUNK 8192
     NOCACHE LOGGING)
LOB (JSON_WITHOUT_SIGNATURE) STORE AS SECUREFILE
    (TABLESPACE USERS
     ENABLE STORAGE IN ROW
     CHUNK 8192
     NOCACHE LOGGING)
LOB (JSON_WITH_SIGNATURE) STORE AS SECUREFILE
    (TABLESPACE USERS
     ENABLE STORAGE IN ROW
     CHUNK 8192
     NOCACHE LOGGING)
LOB (RESPONSE) STORE AS SECUREFILE
    (TABLESPACE USERS
     ENABLE STORAGE IN ROW
     CHUNK 8192
     NOCACHE LOGGING)
LOB (SENT_JSON) STORE AS SECUREFILE
    (TABLESPACE USERS
     ENABLE STORAGE IN ROW
     CHUNK 8192
     NOCACHE LOGGING)
LOB (SERIALIZATION) STORE AS SECUREFILE
    (TABLESPACE USERS
     ENABLE STORAGE IN ROW
     CHUNK 8192
     NOCACHE LOGGING)
TABLESPACE USERS
PCTUSED 0
PCTFREE 10
INITRANS 1
MAXTRANS 255
STORAGE (INITIAL 64 K
         NEXT 1 M
         MINEXTENTS 1
         MAXEXTENTS UNLIMITED
         PCTINCREASE 0
         BUFFER_POOL DEFAULT)
LOGGING
NOCOMPRESS
NOCACHE
MONITORING;