# Generated by Django 5.1.15 on 2026-06-14 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_cash',
            field=models.BooleanField(default=False),
        ),
    ]
