# Generated by Django 5.1.15 on 2026-06-15 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_taxcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxcode',
            name='input_account_code',
            field=models.CharField(default='1190', max_length=32),
        ),
    ]
