# Generated by Django 5.1.15 on 2026-06-16 12:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0004_taxcode_input_account_code'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FixedAsset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('code', models.CharField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(blank=True, default='', max_length=120)),
                ('acquisition_date', models.DateField()),
                ('in_service_date', models.DateField()),
                ('cost_minor', models.BigIntegerField()),
                ('salvage_minor', models.BigIntegerField(default=0)),
                ('useful_life_months', models.IntegerField()),
                ('asset_account_code', models.CharField(default='1500', max_length=32)),
                ('accumulated_account_code', models.CharField(default='1590', max_length=32)),
                ('expense_account_code', models.CharField(default='5300', max_length=32)),
                ('accumulated_depreciation_minor', models.BigIntegerField(default=0)),
                ('months_depreciated', models.IntegerField(default=0)),
                ('acquire_journal_number', models.CharField(blank=True, default='', max_length=32)),
                ('status', models.CharField(choices=[('active', 'Active'), ('disposed', 'Disposed')], default='active', max_length=16)),
                ('disposed_date', models.DateField(blank=True, null=True)),
                ('disposal_proceeds_minor', models.BigIntegerField(blank=True, null=True)),
                ('disposal_gain_loss_minor', models.BigIntegerField(blank=True, null=True)),
                ('disposal_journal_number', models.CharField(blank=True, default='', max_length=32)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.branch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'accounting_fixed_asset',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='DepreciationEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('period_code', models.CharField(max_length=16)),
                ('amount_minor', models.BigIntegerField()),
                ('journal_number', models.CharField(blank=True, default='', max_length=32)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='depreciation_entries', to='accounting.fixedasset')),
            ],
            options={
                'db_table': 'accounting_depreciation_entry',
                'ordering': ['asset', 'period_code'],
                'unique_together': {('asset', 'period_code')},
            },
        ),
    ]
