# Generated by Django 5.1.15 on 2026-06-16 13:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0006_journalline_cost_center_code_costcenter'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankStatement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('account_code', models.CharField(max_length=32)),
                ('statement_date', models.DateField()),
                ('opening_balance_minor', models.BigIntegerField(default=0)),
                ('closing_balance_minor', models.BigIntegerField()),
                ('reference', models.CharField(blank=True, default='', max_length=128)),
                ('status', models.CharField(choices=[('open', 'Open'), ('reconciled', 'Reconciled')], default='open', max_length=16)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.branch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'accounting_bank_statement',
                'ordering': ['-statement_date'],
            },
        ),
        migrations.CreateModel(
            name='BankStatementLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('line_no', models.IntegerField()),
                ('date', models.DateField()),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('amount_minor', models.BigIntegerField()),
                ('matched_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounting.journalline')),
                ('statement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='accounting.bankstatement')),
            ],
            options={
                'db_table': 'accounting_bank_statement_line',
                'ordering': ['statement', 'line_no'],
                'unique_together': {('statement', 'line_no')},
            },
        ),
    ]
