# Generated by Django 5.1.15 on 2026-06-20 23:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0009_reportdefinition'),
        ('identity', '0005_user_status_department_user_department_team_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='identity.department'),
        ),
        migrations.AddField(
            model_name='account',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='identity.team'),
        ),
        migrations.AddField(
            model_name='bankstatement',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='identity.department'),
        ),
        migrations.AddField(
            model_name='bankstatement',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='identity.team'),
        ),
        migrations.AddField(
            model_name='budget',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='identity.department'),
        ),
        migrations.AddField(
            model_name='budget',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='identity.team'),
        ),
        migrations.AddField(
            model_name='costcenter',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='identity.department'),
        ),
        migrations.AddField(
            model_name='costcenter',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='identity.team'),
        ),
        migrations.AddField(
            model_name='fixedasset',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='identity.department'),
        ),
        migrations.AddField(
            model_name='fixedasset',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='identity.team'),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='identity.department'),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='identity.team'),
        ),
        migrations.AddField(
            model_name='reportdefinition',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='identity.department'),
        ),
        migrations.AddField(
            model_name='reportdefinition',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='identity.team'),
        ),
        migrations.AddField(
            model_name='taxcode',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='identity.department'),
        ),
        migrations.AddField(
            model_name='taxcode',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='identity.team'),
        ),
    ]
