# Generated by Django 5.1.15 on 2026-07-02 08:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0011_journalentry_party'),
        ('core', '0001_initial'),
        ('identity', '0009_orgpreferences_order_cancel_until'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['-date', 'number'], name='accounting__date_df13de_idx'),
        ),
    ]
