# Generated by Django 5.1.15 on 2026-07-20 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0012_journalentry_accounting__date_df13de_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='name_ar',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='costcenter',
            name='name_ar',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='taxcode',
            name='name_ar',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
    ]
