# Generated by Django 5.1.15 on 2026-07-04 09:48

import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0002_attachment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('filename', models.CharField(max_length=255)),
                ('media_type', models.CharField(max_length=100)),
                ('size', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('processing', 'processing'), ('ready', 'ready'), ('failed', 'failed')], default='processing', max_length=12)),
                ('error_text', models.CharField(blank=True, default='', max_length=255)),
                ('chunk_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='knowledge_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq', models.PositiveIntegerField()),
                ('text', models.TextField()),
                ('search', django.contrib.postgres.search.SearchVectorField(null=True)),
                ('embedding', models.JSONField(blank=True, null=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='assistant.knowledgedocument')),
            ],
            options={
                'ordering': ['document_id', 'seq'],
                'indexes': [django.contrib.postgres.indexes.GinIndex(fields=['search'], name='assistant_k_search_b2d82e_gin')],
                'constraints': [models.UniqueConstraint(fields=('document', 'seq'), name='uniq_chunk_per_doc_seq')],
            },
        ),
    ]
