# Generated by Django 5.1.15 on 2026-07-09 13:48

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0003_knowledge'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Trace',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('feature', models.CharField(choices=[('chat', 'Chat'), ('ask', 'Ask'), ('agent', 'Agent'), ('extract', 'Extract'), ('digest', 'Digest'), ('suggest', 'Suggest'), ('embed', 'Embed'), ('eval', 'Eval')], max_length=12)),
                ('provider', models.CharField(blank=True, default='', max_length=40)),
                ('model', models.CharField(blank=True, default='', max_length=80)),
                ('prompt_ref', models.CharField(blank=True, default='', max_length=120)),
                ('input_tokens', models.PositiveIntegerField(default=0)),
                ('output_tokens', models.PositiveIntegerField(default=0)),
                ('latency_ms', models.PositiveIntegerField(default=0)),
                ('cost_microcents', models.BigIntegerField(default=0)),
                ('status', models.CharField(choices=[('ok', 'Ok'), ('error', 'Error'), ('timeout', 'Timeout'), ('cancelled', 'Cancelled'), ('guardrail_blocked', 'Guardrail Blocked')], default='ok', max_length=20)),
                ('error_class', models.CharField(blank=True, default='', max_length=40)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_traces', to=settings.AUTH_USER_MODEL)),
                ('conversation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='traces', to='assistant.conversation')),
            ],
        ),
        migrations.CreateModel(
            name='TraceStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq', models.PositiveIntegerField()),
                ('kind', models.CharField(choices=[('llm', 'Llm'), ('tool', 'Tool'), ('retrieval', 'Retrieval'), ('guardrail', 'Guardrail'), ('validation', 'Validation')], max_length=12)),
                ('name', models.CharField(blank=True, default='', max_length=100)),
                ('latency_ms', models.PositiveIntegerField(default=0)),
                ('ok', models.BooleanField(default=True)),
                ('detail', models.JSONField(blank=True, default=dict)),
                ('trace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='assistant.trace')),
            ],
            options={
                'ordering': ['trace_id', 'seq'],
            },
        ),
        migrations.AddIndex(
            model_name='trace',
            index=models.Index(fields=['created_at'], name='assistant_t_created_0898d2_idx'),
        ),
        migrations.AddIndex(
            model_name='trace',
            index=models.Index(fields=['feature', 'created_at'], name='assistant_t_feature_47c785_idx'),
        ),
        migrations.AddIndex(
            model_name='tracestep',
            index=models.Index(fields=['trace', 'seq'], name='assistant_t_trace_i_fdd051_idx'),
        ),
    ]
