# Generated by Django 5.1.15 on 2026-07-11 11:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0004_trace_tracestep_trace_assistant_t_created_0898d2_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResponseCacheVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=20, unique=True)),
                ('version', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ResponseCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=64, unique=True)),
                ('task', models.CharField(max_length=20)),
                ('response', models.JSONField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('hit_count', models.PositiveIntegerField(default=0)),
                ('input_version', models.PositiveIntegerField(default=0)),
            ],
            options={
                'indexes': [models.Index(fields=['task', 'created_at'], name='assistant_r_task_829fbd_idx')],
            },
        ),
    ]
