# Generated by Django 5.1.15 on 2026-07-11 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0005_responsecacheversion_responsecache'),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(choices=[('request', 'Request'), ('user', 'User'), ('org', 'Org')], max_length=10, unique=True)),
                ('limit_microcents', models.BigIntegerField()),
                ('action', models.CharField(choices=[('block', 'Block'), ('notify', 'Notify')], default='block', max_length=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SpendRollup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(choices=[('request', 'Request'), ('user', 'User'), ('org', 'Org')], max_length=10)),
                ('scope_key', models.CharField(max_length=64)),
                ('period', models.DateField()),
                ('spend_microcents', models.BigIntegerField(default=0)),
            ],
            options={
                'indexes': [models.Index(fields=['scope', 'period'], name='assistant_s_scope_ec4cb7_idx')],
                'constraints': [models.UniqueConstraint(fields=('scope', 'scope_key', 'period'), name='uniq_spend_rollup_scope_key_period')],
            },
        ),
    ]
