# Generated by Django 5.1.15 on 2026-07-18 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0008_semanticcache'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trace',
            name='feature',
            field=models.CharField(choices=[('chat', 'Chat'), ('ask', 'Ask'), ('agent', 'Agent'), ('extract', 'Extract'), ('digest', 'Digest'), ('suggest', 'Suggest'), ('embed', 'Embed'), ('eval', 'Eval'), ('workflow', 'Workflow')], max_length=12),
        ),
    ]
