# Generated by Django 5.1.15 on 2026-07-27 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0010_knowledgechunk_pgvector'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trace',
            name='feature',
            field=models.CharField(choices=[('chat', 'Chat'), ('ask', 'Ask'), ('agent', 'Agent'), ('extract', 'Extract'), ('digest', 'Digest'), ('suggest', 'Suggest'), ('embed', 'Embed'), ('eval', 'Eval'), ('workflow', 'Workflow'), ('rerank', 'Rerank')], max_length=12),
        ),
    ]
