# Generated by Django 5.1.15 on 2026-07-30 09:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0012_conversation_summary_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrgMemory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('slot', 'Slot'), ('fact', 'Fact')], max_length=8)),
                ('key', models.CharField(blank=True, default='', max_length=48)),
                ('value', models.TextField()),
                ('embedding', models.JSONField(blank=True, null=True)),
                ('source', models.CharField(choices=[('explicit', 'Explicit'), ('pattern', 'Pattern'), ('settings', 'Settings')], max_length=10)),
                ('confidence', models.PositiveSmallIntegerField(default=100)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('superseded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='assistant.orgmemory')),
                ('written_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_org_memories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
                'constraints': [models.UniqueConstraint(condition=models.Q(('kind', 'slot'), ('superseded_by__isnull', True)), fields=('key',), name='uniq_active_org_memory_slot')],
            },
        ),
        migrations.CreateModel(
            name='UserMemory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('slot', 'Slot'), ('fact', 'Fact')], max_length=8)),
                ('key', models.CharField(blank=True, default='', max_length=48)),
                ('value', models.TextField()),
                ('embedding', models.JSONField(blank=True, null=True)),
                ('source', models.CharField(choices=[('explicit', 'Explicit'), ('pattern', 'Pattern'), ('settings', 'Settings')], max_length=10)),
                ('confidence', models.PositiveSmallIntegerField(default=100)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('superseded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='assistant.usermemory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_memories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
                'indexes': [models.Index(fields=['user', 'kind'], name='assistant_u_user_id_df5626_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('kind', 'slot'), ('superseded_by__isnull', True)), fields=('user', 'key'), name='uniq_active_user_memory_slot')],
            },
        ),
    ]
