# Generated by Django 5.1.15 on 2026-08-15 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0015_detached_streaming'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentrun',
            name='parked',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='agentrun',
            name='status',
            field=models.CharField(choices=[('planning', 'Planning'), ('running', 'Running'), ('waiting_confirm', 'Waiting Confirm'), ('waiting_clarify', 'Waiting Clarify'), ('paused', 'Paused'), ('done', 'Done'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='running', max_length=16),
        ),
    ]
