# Generated by Django 5.1.15 on 2026-06-15 21:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ETAInvoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('invoice_number', models.CharField(max_length=32, unique=True)),
                ('order_number', models.CharField(blank=True, default='', max_length=32)),
                ('customer_code', models.CharField(blank=True, default='', max_length=32)),
                ('customer_name', models.CharField(blank=True, default='', max_length=200)),
                ('issue_date', models.DateField()),
                ('currency', models.CharField(default='EGP', max_length=3)),
                ('tax_code', models.CharField(blank=True, default='', max_length=16)),
                ('net_minor', models.BigIntegerField(default=0)),
                ('tax_minor', models.BigIntegerField(default=0)),
                ('total_minor', models.BigIntegerField(default=0)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('valid', 'Valid'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='draft', max_length=16)),
                ('uuid', models.CharField(blank=True, default='', max_length=64)),
                ('document_hash', models.CharField(blank=True, default='', max_length=64)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('error_text', models.CharField(blank=True, default='', max_length=255)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.branch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'einvoice_eta_invoice',
                'ordering': ['-issue_date', '-created_at'],
                'indexes': [models.Index(fields=['status'], name='einvoice_et_status_a6435e_idx'), models.Index(fields=['customer_code'], name='einvoice_et_custome_e14bc3_idx')],
            },
        ),
    ]
