# Generated by Django 5.1.15 on 2026-07-21 02:59

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('einvoice', '0002_etainvoice_department_etainvoice_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='ETASettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('environment', models.CharField(blank=True, choices=[('sandbox', 'Pre-production'), ('production', 'Production')], default='', max_length=16)),
                ('identity_url', models.CharField(blank=True, default='', max_length=255)),
                ('api_base_url', models.CharField(blank=True, default='', max_length=255)),
                ('client_id', models.CharField(blank=True, default='', max_length=128)),
                ('rin', models.CharField(blank=True, default='', max_length=32)),
                ('client_secret_encrypted', models.TextField(blank=True, default='')),
                ('enabled', models.BooleanField(default=False)),
                ('last_test_ok_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'ETA settings',
                'verbose_name_plural': 'ETA settings',
                'db_table': 'einvoice_eta_settings',
            },
        ),
    ]
