# Generated by Django 5.1.15 on 2026-07-21 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('einvoice', '0004_etainvoice_long_id_submission_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='etainvoice',
            name='customer_national_id',
            field=models.CharField(blank=True, default='', max_length=14),
        ),
        migrations.AddField(
            model_name='etainvoice',
            name='customer_tax_registration_number',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
    ]
