# Generated by Django 5.1.15 on 2026-07-21 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('einvoice', '0005_etainvoice_customer_national_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='etainvoice',
            name='next_poll_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='etainvoice',
            name='poll_attempts',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='etainvoice',
            name='poll_stalled',
            field=models.BooleanField(default=False),
        ),
    ]
