# Generated by Django 5.1.15 on 2026-07-21 20:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('einvoice', '0006_etainvoice_next_poll_at_etainvoice_poll_attempts_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ETAInvoiceArchive',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document_json', models.TextField(blank=True, default='')),
                ('response_json', models.TextField(blank=True, default='')),
                ('document_hash', models.CharField(blank=True, default='', max_length=64)),
                ('simulated', models.BooleanField(default=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('eta_invoice', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='archive', to='einvoice.etainvoice')),
            ],
            options={
                'db_table': 'einvoice_eta_invoice_archive',
                'ordering': ['-archived_at'],
            },
        ),
    ]
