# Generated by Django 5.1.15 on 2026-07-21 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('einvoice', '0007_etainvoicearchive'),
    ]

    operations = [
        migrations.AddField(
            model_name='etainvoice',
            name='lines_json',
            field=models.TextField(blank=True, default=''),
        ),
    ]
