# Generated by Django 5.1.15 on 2026-06-14 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('module', models.CharField(max_length=64)),
                ('action', models.CharField(max_length=128)),
                ('entity_type', models.CharField(max_length=128)),
                ('entity_id', models.CharField(blank=True, max_length=64)),
                ('before', models.JSONField(blank=True, null=True)),
                ('after', models.JSONField(blank=True, null=True)),
                ('result', models.CharField(choices=[('success', 'Success'), ('failure', 'Failure')], default='success', max_length=16)),
                ('correlation_id', models.CharField(blank=True, db_index=True, max_length=64)),
            ],
            options={
                'db_table': 'audit_entry',
                'ordering': ['-created_at'],
            },
        ),
    ]
