# Generated by Django 5.1.15 on 2026-07-02 08:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('crm', '0003_activity_department_activity_team_and_more'),
        ('identity', '0009_orgpreferences_order_cancel_until'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='opportunity',
            index=models.Index(fields=['-created_at'], name='crm_opportu_created_40fe24_idx'),
        ),
    ]
