# Generated by Django 5.1.15 on 2026-06-15 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmovement',
            name='type',
            field=models.CharField(choices=[('receipt', 'Receipt'), ('issue', 'Issue'), ('transfer', 'Transfer'), ('return_in', 'Customer return (in)'), ('return_out', 'Supplier return (out)')], max_length=16),
        ),
    ]
