# Generated by Django 5.1.15 on 2026-06-16 20:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('inventory', '0002_alter_stockmovement_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockCount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('count_date', models.DateField()),
                ('reference', models.CharField(blank=True, default='', max_length=128)),
                ('memo', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('counting', 'Counting'), ('posted', 'Posted'), ('cancelled', 'Cancelled')], default='counting', max_length=16)),
            ],
            options={
                'db_table': 'inventory_stock_count',
                'ordering': ['-count_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StockCountLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('system_quantity', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('counted_quantity', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('variance_quantity', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('variance_value_minor', models.BigIntegerField(default=0)),
            ],
            options={
                'db_table': 'inventory_stock_count_line',
                'ordering': ['count', 'item__sku'],
            },
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='batch_no',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='type',
            field=models.CharField(choices=[('receipt', 'Receipt'), ('issue', 'Issue'), ('transfer', 'Transfer'), ('return_in', 'Customer return (in)'), ('return_out', 'Supplier return (out)'), ('adjustment', 'Count adjustment')], max_length=16),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['batch_no'], name='inventory_s_batch_n_e284f1_idx'),
        ),
        migrations.AddField(
            model_name='stockcount',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.branch'),
        ),
        migrations.AddField(
            model_name='stockcount',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stockcount',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stockcount',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_counts', to='inventory.warehouse'),
        ),
        migrations.AddField(
            model_name='stockcountline',
            name='count',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='inventory.stockcount'),
        ),
        migrations.AddField(
            model_name='stockcountline',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='inventory.item'),
        ),
        migrations.AddField(
            model_name='stockcountline',
            name='movement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='inventory.stockmovement'),
        ),
        migrations.AlterUniqueTogether(
            name='stockcountline',
            unique_together={('count', 'item')},
        ),
    ]
