# Generated by Django 5.1.15 on 2026-06-20 23:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0005_user_status_department_user_department_team_and_more'),
        ('inventory', '0003_stockcount_stockcountline_stockmovement_batch_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='identity.department'),
        ),
        migrations.AddField(
            model_name='item',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='identity.team'),
        ),
        migrations.AddField(
            model_name='stockcount',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='identity.department'),
        ),
        migrations.AddField(
            model_name='stockcount',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='identity.team'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='identity.department'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='identity.team'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='identity.department'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='identity.team'),
        ),
    ]
