# Generated by Django 5.1.15 on 2026-07-02 08:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('identity', '0009_orgpreferences_order_cancel_until'),
        ('inventory', '0004_item_department_item_team_stockcount_department_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['-date', '-created_at'], name='inventory_s_date_97f545_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['reference'], name='inventory_s_referen_feeeae_idx'),
        ),
    ]
