# Generated by Django 5.1.15 on 2026-07-17 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_stocktransfer'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='custom_data',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
