# Generated by Django 5.1.15 on 2026-07-17 19:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_customfielddef'),
        ('identity', '0011_apikey'),
        ('inventory', '0007_item_custom_data'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmovement',
            name='type',
            field=models.CharField(choices=[('receipt', 'Receipt'), ('issue', 'Issue'), ('transfer', 'Transfer'), ('return_in', 'Customer return (in)'), ('return_out', 'Supplier return (out)'), ('adjustment', 'Count adjustment'), ('opening', 'Opening balance')], max_length=16),
        ),
        migrations.CreateModel(
            name='PendingStockEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=18)),
                ('unit_cost_minor', models.BigIntegerField()),
                ('date', models.DateField()),
                ('type', models.CharField(choices=[('opening', 'Opening balance')], default='opening', max_length=16)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('applied', 'Applied'), ('discarded', 'Discarded')], default='pending', max_length=16)),
                ('suspense_account', models.CharField(blank=True, default='', max_length=32)),
                ('batch_ref', models.CharField(blank=True, default='', max_length=64)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('applied_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.branch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='identity.department')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pending_stock_entries', to='inventory.item')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='identity.team')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pending_stock_entries', to='inventory.warehouse')),
            ],
            options={
                'db_table': 'inventory_pending_stock_entry',
                'ordering': ['-date', '-created_at'],
                'indexes': [models.Index(fields=['status'], name='inventory_p_status_0f91eb_idx')],
            },
        ),
    ]
