# Generated by Django 5.1.15 on 2026-07-21 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_alter_stockmovement_type_pendingstockentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='eta_code_status',
            field=models.CharField(choices=[('not_submitted', 'Not submitted'), ('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='not_submitted', max_length=16),
        ),
        migrations.AddField(
            model_name='item',
            name='eta_item_code',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='item',
            name='gpc_code',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
    ]
