# Generated by Django 5.1.15 on 2026-07-22 08:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_backfill_branch_arabic_names'),
        ('identity', '0015_merge_20260721_0552'),
        ('inventory', '0009_item_eta_coding'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierItemAlias',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('supplier_code', models.CharField(max_length=32)),
                ('supplier_item_code', models.CharField(blank=True, default='', max_length=64)),
                ('supplier_item_name', models.CharField(blank=True, default='', max_length=200)),
                ('source', models.CharField(choices=[('confirmed', 'Confirmed'), ('imported', 'Imported'), ('manual', 'Manual')], default='confirmed', max_length=16)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.branch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='identity.department')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_aliases', to='inventory.item')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='identity.team')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'inventory_supplier_item_alias',
                'ordering': ['supplier_code', 'supplier_item_code'],
                'indexes': [models.Index(fields=['supplier_code', 'supplier_item_code'], name='inventory_s_supplie_1d5c40_idx'), models.Index(fields=['item'], name='inventory_s_item_id_19ceff_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('supplier_item_code', ''), _negated=True), fields=('supplier_code', 'supplier_item_code'), name='uniq_supplier_item_code')],
            },
        ),
    ]
