# Generated by Django 5.1.15 on 2026-07-22 08:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_backfill_branch_arabic_names'),
        ('identity', '0015_merge_20260721_0552'),
        ('inventory', '0010_supplieritemalias'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='barcode',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='item',
            name='mpn',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['barcode'], name='inventory_i_barcode_209767_idx'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['mpn'], name='inventory_i_mpn_222806_idx'),
        ),
        migrations.AddConstraint(
            model_name='item',
            constraint=models.UniqueConstraint(condition=models.Q(('barcode', ''), _negated=True), fields=('barcode',), name='uniq_item_barcode'),
        ),
        migrations.AddConstraint(
            model_name='item',
            constraint=models.UniqueConstraint(condition=models.Q(('mpn', ''), _negated=True), fields=('mpn',), name='uniq_item_mpn'),
        ),
    ]
