"""Gate 17 — API schema snapshot, additive-only (twenty-harvest FILE_03).

Twenty's `ci-breaking-changes.yaml` reference: diff the API surface on every change. This
codebase's views are plain DRF `APIView`s (verbs defined directly on the class, no
ViewSet/router, no per-view `serializer_class` attribute — serializers are instantiated by hand
inside each method), so the snapshot inventories two things separately instead of one
route->serializer tree:

  routes:      every api/* endpoint -> its HTTP methods (methods defined directly on the view
               class) and the view class name.
  serializers: every declared `rest_framework.serializers.Serializer`/`ModelSerializer` under
               erp/*/api/serializers.py -> its fields -> {type, required}.

Snapshot lives at scripts/gates/snapshots/api_schema.json (sorted, stable). Missing on first run
-> gate creates it and passes (bootstrap, mirrors gate16's fixture pattern). Otherwise: a removed
route, removed HTTP method, removed serializer, removed field, a field's type changing, or a
field becoming required when it wasn't -> exit 1 (breaking). New routes/methods/serializers/
fields, or a field becoming optional, pass with a printed note — the snapshot is NOT auto-
rewritten, so an intentional change (breaking or not) is regenerated by hand: delete the snapshot
and re-run the gate, then commit the new file — the diff in review IS the approval.
"""
from __future__ import annotations

import importlib
import json
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent.parent
SNAPSHOT = REPO_ROOT / "scripts" / "gates" / "snapshots" / "api_schema.json"
HTTP_METHODS = ("get", "post", "put", "patch", "delete", "head", "options")


def _routes() -> list[dict]:
    from django.urls import get_resolver
    from rest_framework.views import APIView

    def walk(resolver, prefix=""):
        for p in resolver.url_patterns:
            route = prefix + str(p.pattern)
            if hasattr(p, "url_patterns"):
                yield from walk(p, route)
            else:
                yield route, p.callback

    routes = []
    for route, callback in walk(get_resolver()):
        if not route.startswith("api/"):
            continue
        view_cls = getattr(callback, "cls", None) or getattr(callback, "view_class", None)
        if view_cls is None or not issubclass(view_cls, APIView):
            continue
        methods = sorted(m.upper() for m in HTTP_METHODS if m in vars(view_cls))
        if not methods:
            continue
        routes.append({"path": route, "view": view_cls.__name__, "methods": methods})
    routes.sort(key=lambda r: (r["path"], r["view"]))
    return routes


def _serializer_modules():
    for path in sorted((REPO_ROOT / "erp").glob("*/api/serializers.py")):
        app = path.parent.parent.name
        yield f"erp.{app}.api.serializers"


def _serializers() -> dict:
    from rest_framework.serializers import BaseSerializer, ListSerializer

    out: dict[str, dict] = {}
    for mod_name in _serializer_modules():
        module = importlib.import_module(mod_name)
        for name, obj in vars(module).items():
            if not (
                isinstance(obj, type)
                and issubclass(obj, BaseSerializer)
                and obj.__module__ == module.__name__
            ):
                continue
            try:
                instance = obj()
            except TypeError:
                continue
            fields = {}
            for fname, field in instance.get_fields().items():
                ftype = type(field).__name__
                if isinstance(field, ListSerializer):
                    ftype = f"ListSerializer[{type(field.child).__name__}]"
                fields[fname] = {"type": ftype, "required": bool(field.required)}
            out[f"{mod_name}.{name}"] = fields
    return out


def _build_snapshot() -> dict:
    return {"routes": _routes(), "serializers": _serializers()}


def _diff(old: dict, new: dict) -> list[str]:
    breaking: list[str] = []

    old_routes = {r["path"]: r for r in old.get("routes", [])}
    new_routes = {r["path"]: r for r in new.get("routes", [])}
    for path, old_r in old_routes.items():
        new_r = new_routes.get(path)
        if new_r is None:
            breaking.append(f"removed route: {path}")
            continue
        removed_methods = set(old_r["methods"]) - set(new_r["methods"])
        if removed_methods:
            breaking.append(f"removed method(s) on {path}: {sorted(removed_methods)}")

    old_ser = old.get("serializers", {})
    new_ser = new.get("serializers", {})
    for ser_name, old_fields in old_ser.items():
        new_fields = new_ser.get(ser_name)
        if new_fields is None:
            breaking.append(f"removed serializer: {ser_name}")
            continue
        for fname, old_f in old_fields.items():
            new_f = new_fields.get(fname)
            if new_f is None:
                breaking.append(f"removed field: {ser_name}.{fname}")
                continue
            if new_f["type"] != old_f["type"]:
                breaking.append(
                    f"type changed: {ser_name}.{fname} {old_f['type']} -> {new_f['type']}"
                )
            if new_f["required"] and not old_f["required"]:
                breaking.append(f"field became required: {ser_name}.{fname}")
    return breaking


def check() -> None:
    new_snapshot = _build_snapshot()

    if not SNAPSHOT.exists():
        SNAPSHOT.parent.mkdir(parents=True, exist_ok=True)
        SNAPSHOT.write_text(json.dumps(new_snapshot, indent=2, sort_keys=True) + "\n", encoding="utf-8")
        print(f"GATE 17: snapshot missing — created {SNAPSHOT} (bootstrap). Commit it.")
        return

    old_snapshot = json.loads(SNAPSHOT.read_text(encoding="utf-8"))
    breaking = _diff(old_snapshot, new_snapshot)
    if breaking:
        raise AssertionError(
            "API schema regressed (breaking):\n  " + "\n  ".join(breaking) +
            f"\nIf intentional, delete {SNAPSHOT}, re-run this gate to regenerate it, and commit."
        )

    added_routes = {r["path"] for r in new_snapshot["routes"]} - {
        r["path"] for r in old_snapshot.get("routes", [])
    }
    added_serializers = set(new_snapshot["serializers"]) - set(old_snapshot.get("serializers", {}))
    if added_routes:
        print(f"GATE 17: {len(added_routes)} new route(s) (non-breaking): {sorted(added_routes)}")
    if added_serializers:
        print(f"GATE 17: {len(added_serializers)} new serializer(s) (non-breaking): {sorted(added_serializers)}")
    print("GATE 17: API schema check OK")
