# Generated by Django 5.1.15 on 2026-06-15 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='debit_note_number',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='returned_minor',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='purchaseorderline',
            name='returned_qty',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('confirmed', 'Confirmed'), ('partially_received', 'Partially received'), ('received', 'Received'), ('billed', 'Billed'), ('paid', 'Paid'), ('returned', 'Returned'), ('cancelled', 'Cancelled')], default='draft', max_length=24),
        ),
    ]
