# Generated by Django 5.1.15 on 2026-06-15 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0004_purchaseorder_approved_purchaseorder_approved_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='tax_code',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='tax_minor',
            field=models.BigIntegerField(default=0),
        ),
    ]
