# Generated by Django 5.1.15 on 2026-06-20 23:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0005_user_status_department_user_department_team_and_more'),
        ('purchasing', '0005_purchaseorder_tax_code_purchaseorder_tax_minor'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='identity.department'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='identity.team'),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='identity.department'),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='identity.team'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='identity.department'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='identity.team'),
        ),
    ]
