# Generated by Django 5.1.15 on 2026-07-02 08:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('identity', '0009_orgpreferences_order_cancel_until'),
        ('purchasing', '0006_purchaseorder_department_purchaseorder_team_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['-order_date', '-created_at'], name='purchasing__order_d_ca8945_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaserequest',
            index=models.Index(fields=['-request_date', '-created_at'], name='purchasing__request_c12f24_idx'),
        ),
    ]
