# Generated by Django 5.1.15 on 2026-07-17 17:53

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_customfielddef'),
        ('identity', '0011_apikey'),
        ('purchasing', '0007_purchaseorder_purchasing__order_d_ca8945_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingPayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('party_code', models.CharField(max_length=32)),
                ('amount_minor', models.BigIntegerField()),
                ('date', models.DateField()),
                ('method', models.CharField(blank=True, default='', max_length=16)),
                ('source', models.CharField(default='import', max_length=16)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('applied', 'Applied'), ('discarded', 'Discarded')], default='pending', max_length=16)),
                ('batch_ref', models.CharField(blank=True, default='', max_length=64)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('applied_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.branch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='identity.department')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pending_payments', to='purchasing.purchaseorder')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='identity.team')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'purchasing_pending_payment',
                'ordering': ['-date', '-created_at'],
                'indexes': [models.Index(fields=['status'], name='purchasing__status_a85178_idx'), models.Index(fields=['order'], name='purchasing__order_i_6879f5_idx')],
            },
        ),
    ]
