# Generated by Django 5.1.15 on 2026-07-18 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0008_pendingpayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='custom_data',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
