# Generated by Django 5.1.15 on 2026-07-24 09:07

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('imports', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workflow_key', models.CharField(max_length=64)),
                ('entity_type', models.CharField(blank=True, default='', max_length=64)),
                ('related_entity_id', models.CharField(blank=True, default='', max_length=64)),
                ('status', models.CharField(choices=[('active', 'active'), ('completed', 'completed'), ('discarded', 'discarded'), ('superseded', 'superseded')], default='active', max_length=16)),
                ('payload', models.JSONField(default=dict)),
                ('schema_version', models.PositiveIntegerField(default=1)),
                ('client_version', models.PositiveIntegerField(default=0)),
                ('last_active_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('import_batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='imports.importbatch')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'worksessions_session',
                'ordering': ['-last_active_at'],
                'indexes': [models.Index(fields=['owner', 'workflow_key', 'status'], name='worksession_owner_i_37a5a3_idx'), models.Index(fields=['owner', 'status', 'last_active_at'], name='worksession_owner_i_7f4b74_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('owner', 'workflow_key', 'related_entity_id'), name='uniq_active_worksession_per_form')],
            },
        ),
    ]
