# Generated by Django 5.1.15 on 2026-09-24 10:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InstalledLicense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_text', models.TextField(blank=True, default='')),
                ('installed_at', models.DateTimeField(blank=True, null=True)),
                ('first_run_at', models.DateTimeField(blank=True, null=True)),
                ('last_seen_date', models.DateField(blank=True, null=True)),
                ('installed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'installed license',
                'verbose_name_plural': 'installed license',
            },
        ),
    ]
