# Generated by Django 5.1.15 on 2026-09-24 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licensing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='installedlicense',
            name='clock_rollback_flagged',
            field=models.BooleanField(default=False),
        ),
    ]
