# Generated by Django 5.1.15 on 2026-07-02 08:31

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IdempotencyKey',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('endpoint', models.CharField(max_length=64)),
                ('key', models.CharField(max_length=128)),
                ('object_id', models.CharField(blank=True, default='', max_length=64)),
            ],
            options={
                'db_table': 'core_idempotency_key',
                'unique_together': {('endpoint', 'key')},
            },
        ),
    ]
