# Generated by Django 5.1.15 on 2026-07-17 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_appliedupgradestep'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomFieldDef',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_key', models.CharField(choices=[('sales.customer', 'Customer'), ('inventory.item', 'Item')], max_length=32)),
                ('key', models.SlugField(max_length=64)),
                ('label_ar', models.CharField(max_length=100)),
                ('label_en', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('TEXT', 'Text'), ('NUMBER', 'Number'), ('DATE', 'Date'), ('CHOICE', 'Choice'), ('MONEY', 'Money')], max_length=16)),
                ('required', models.BooleanField(default=False)),
                ('choices', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('position', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'core_custom_field_def',
                'ordering': ['entity_key', 'position', 'key'],
                'unique_together': {('entity_key', 'key')},
            },
        ),
    ]
