# Generated by Django 5.1.15 on 2026-07-20 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_customfielddef'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='name_ar',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='customfielddef',
            name='entity_key',
            field=models.CharField(choices=[('sales.customer', 'Customer'), ('inventory.item', 'Item'), ('purchasing.supplier', 'Supplier')], max_length=32),
        ),
    ]
